# Generated by Django 5.0.7 on 2024-07-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=23)),
                ('city', models.CharField(max_length=23)),
                ('gender', models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], max_length=23)),
                ('profile_pic', models.ImageField(upload_to='Profile')),
            ],
        ),
    ]
